name: provider_temp_gen
description: provider_base_tools Template Generation Tool. This is the provider_base_tools template generator, please integrate the provider_base_tools first Reuse this plugin
version: 1.0.6
homepage: https://github.com/km511928426/provider_temp_gen
repository: https://github.com/km511928426/provider_temp_gen

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.0
  args: ^2.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  provider_temp_gen: provider_temp_gen